{% set version = '1.0.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-svdialogs
  version: {{ version|replace("-", "_") }}

source:
  fn: svDialogs_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/svDialogs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/svDialogs/svDialogs_{{ version }}.tar.gz
  sha256: 275d805627d85ef16b00ffd548ec466357b6f8f2119735099adc72e59abf1777

build:
  noarch: generic
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, knitr, testthat
requirements:
  host:
    - r-base
    - r-rstudioapi >=0.7
    - r-svgui >=1.0.0
  run:
    - r-base
    - r-rstudioapi >=0.7
    - r-svgui >=1.0.0

test:
  commands:
    - $R -e "library('svDialogs')"           # [not win]
    - "\"%R%\" -e \"library('svDialogs')\""  # [win]

about:
  home: https://github.com/SciViews/svDialogs, http://www.sciviews.org/SciViews-R
  license: GPL-2
  summary: Rapidly construct standard dialog boxes for your GUI, including  message boxes, input
    boxes, list, file or directory selection, ... In case R cannot display GUI dialog
    boxes, a simpler command line version of these interactive elements is also provided
    as fallback solution.
  license_family: GPL2

extra:
  recipe-maintainers:
    - dpryan79
    - johanneskoester
    - bgruening
