{% set version = "1.0.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-svdialogs
  version: {{ version|replace("-", "_") }}

source:
  fn: svDialogs_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/svDialogs_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/svDialogs/svDialogs_{{ version }}.tar.gz
  sha256: 275d805627d85ef16b00ffd548ec466357b6f8f2119735099adc72e59abf1777

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
    - r-svgui >=0.9_52

  run:
    - r-base
    - r-svgui >=0.9_52

test:
  commands:
    - $R -e "library('svDialogs')"  # [not win]
    - "\"%R%\" -e \"library('svDialogs')\""  # [win]

about:
  home: http://www.sciviews.org/SciViews-R
  license: GPL-2
  summary: Rapidly construct dialog boxes for your GUI, including an automatic function assistant
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
