{% set version = "1.1.1" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-svdialogs
  version: {{ version|replace("-", "_") }}

source:
  fn: svDialogs_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/svDialogs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/svDialogs/svDialogs_{{ version }}.tar.gz
  sha256: 8790e734b851a4c74953b5af2e451ec35bdb1f3e68b0dfe13e0fb03577cd671d

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, knitr, testthat
requirements:
  host:
    - r-base
    - r-rstudioapi >=0.7
    - r-svgui >=1.0.0
  run:
    - r-base
    - r-rstudioapi >=0.7
    - r-svgui >=1.0.0

test:
  commands:
    - $R -e "library('svDialogs')"           # [not win]
    - "\"%R%\" -e \"library('svDialogs')\""  # [win]

about:
  home: https://github.com/SciViews/svDialogs, http://www.sciviews.org/SciViews-R
  license: GPL-2.0-only
  summary: Rapidly construct standard dialog boxes for your GUI, including  message boxes, input boxes, list, file or directory selection, ... In case R cannot display GUI dialog boxes, a simpler command line version of these interactive elements is also provided as fallback solution.
  license_family: GPL2

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - johanneskoester
    - bgruening
