# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "avJA3KynUm+zDxIcfZwkEhhkJ1WmQy9RZm88phTm7PggmM6JWN95QLgOtm7ozGzJ6H7PBXxiQixOkemjqyygQBX/EM9FjCF29rP4c5cJ00FqnS2VBgm0oFKCn7+Fp7G7v2rKG1CttJZ/mpXbmKE1n69DcS0fjoDxgfcMbeLCZvBuvoBQUCOBolkjN7EsoS4uDSn8fQ8bv8mn9uRN1jXoM36KXQ2EXwldNh9UcZM/kW/pNwMij0WwMw/pdHCgDQ67ywp1mJYhyIyCa3KctG6B0WBLck49RTytnnG+BJljLgC8lyBI75u6Fjyu51wzHMUBGHmYt0g/levpZpbSt9cmCKLwVf/bDQ71bUSq+dUdkVo83cNk4M7KGFkWpzWUM+TGfXr6LLqUEK/DYto+os7YOkt37Q0bxKjO11vTOVpJCinYflEGWGp8xsocS/6Zht0brnHrZZryyEyC+PQCK3dgmBi+MQZ/qgjbefyR/ztnZqmD7Yc05ocdV0SNl9Ymu1WMWzPzS/wEoVzve2hTYwgF6djaHaZ8PWvUPSl53ugZRD9ar8LkZgzFtrlK7v7jOToP7VzWYrOXhDbG6DoengG0eZp800zh1LUBPfCANnhkP6aIpjXY1OdUlljQpZZIquf6MoGWU7kaoxGhO9+/b++jV5aeVeJvdp+p8TI9YqX52VA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
