appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: avJA3KynUm+zDxIcfZwkEhhkJ1WmQy9RZm88phTm7PggmM6JWN95QLgOtm7ozGzJ6H7PBXxiQixOkemjqyygQBX/EM9FjCF29rP4c5cJ00FqnS2VBgm0oFKCn7+Fp7G7v2rKG1CttJZ/mpXbmKE1n69DcS0fjoDxgfcMbeLCZvBuvoBQUCOBolkjN7EsoS4uDSn8fQ8bv8mn9uRN1jXoM36KXQ2EXwldNh9UcZM/kW/pNwMij0WwMw/pdHCgDQ67ywp1mJYhyIyCa3KctG6B0WBLck49RTytnnG+BJljLgC8lyBI75u6Fjyu51wzHMUBGHmYt0g/levpZpbSt9cmCKLwVf/bDQ71bUSq+dUdkVo83cNk4M7KGFkWpzWUM+TGfXr6LLqUEK/DYto+os7YOkt37Q0bxKjO11vTOVpJCinYflEGWGp8xsocS/6Zht0brnHrZZryyEyC+PQCK3dgmBi+MQZ/qgjbefyR/ztnZqmD7Yc05ocdV0SNl9Ymu1WMWzPzS/wEoVzve2hTYwgF6djaHaZ8PWvUPSl53ugZRD9ar8LkZgzFtrlK7v7jOToP7VzWYrOXhDbG6DoengG0eZp800zh1LUBPfCANnhkP6aIpjXY1OdUlljQpZZIquf6MoGWU7kaoxGhO9+/b++jV5aeVeJvdp+p8TI9YqX52VA=}
