travis:
  secure:
    BINSTAR_TOKEN: xo6fTnWXSjWNFX5bfqo/qhWly2cMY8S0OOCY6Jl2JHK5jEfQpF0LtIHTCjWBcFQP7/zOm4p0P2FvlyZZIXOm4FutWtL/Y+xPlgoAlZ+np5bKHDuY4t58tNhlPKA9K0dhT0KVizBe8tLB9Dk8QAbHEPjtlsdKFZtq8/wB+2rld/v8XVgnuW4hoNszfijjem+D6X+DgWqGKGX0CJEij6OrgNfRCa5FWiyIgQYWKPAcVe3PBHKA05lhsYovD6ewjndhCCEvYEMrp+C0sWtTcXamrYSLjSI0nuclSNKHmfeg36w7iqC0MeW4Dv1qhEJ2e63pwksaZP8BrOPT9cMI3tnEJwe6VNEOAmtLawaFp5TWgKQ47R992RoZaCvvrv/jNkrZeAQRpueor3D22aiVvznmB+KlHWpND+gq3LTzCV5EgavtADDV1gLqCcH/09NkEL0ntYHKxpCoyoofAwVTyN/eJOKbKwSv5m2ks6dzVj+Dtj1oN+U5W+BZa+AGMOTV8aEWe56cjTDFZBUPBD7ZAZ3LBi2jj4dWw/xGenQuPpJ2qiZMNKwabTcZHImSZkCE2GzF27tAx9QGH304ykvQFtCSWsSqsfVasG/00/nQ1wh7sY0sM71meIyLiMtOBi77uCi5oimmilDrVI+/06zKw1f70SGLG5lrfZ3OjILBBDSKShA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
